/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package kafshagaruese_shk2;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author RigonPira
 */
public class Hipodromi extends javax.swing.JFrame {

    /**
     * Creates new form Hipodromi
     */
    public Hipodromi() {
        initComponents();
        this.setLocationRelativeTo(null);
        this.setTitle("Gara me kuaj");
    }
    
    public JLabel getKaliPare(){
        return kaliPare;
    }
    public JLabel getKaliDyte(){
        return kaliDyte;
    }
    public JLabel getKaliTrete(){
        return kaliTrete;
    }
    public JLabel getKaliKatert(){
        return kaliKatert;
    }
    public JLabel getFinish(){
        return finish;
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        kaliDyte = new javax.swing.JLabel();
        kaliPare = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        kaliTrete = new javax.swing.JLabel();
        kaliKatert = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        finish = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        rezultati = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        kaliDyte.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/output-onlinegiftools.gif"))); // NOI18N
        getContentPane().add(kaliDyte);
        kaliDyte.setBounds(60, 180, 140, 70);

        kaliPare.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/output-onlinegiftools.gif"))); // NOI18N
        kaliPare.setText("jLabel4");
        getContentPane().add(kaliPare);
        kaliPare.setBounds(60, 80, 120, 70);

        jLabel2.setFont(new java.awt.Font("Book Antiqua", 1, 36)); // NOI18N
        jLabel2.setText("Gara me Kuaj");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(290, 10, 228, 45);

        kaliTrete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/output-onlinegiftools.gif"))); // NOI18N
        getContentPane().add(kaliTrete);
        kaliTrete.setBounds(60, 280, 110, 70);

        kaliKatert.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/output-onlinegiftools.gif"))); // NOI18N
        getContentPane().add(kaliKatert);
        kaliKatert.setBounds(60, 380, 110, 80);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/istockphoto-1158213985-612x612.jpg"))); // NOI18N
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 70, 610, 410);

        finish.setBackground(new java.awt.Color(255, 0, 0));
        finish.setFont(new java.awt.Font("Sitka Heading", 1, 18)); // NOI18N
        finish.setText("FINISH");
        finish.setOpaque(true);
        getContentPane().add(finish);
        finish.setBounds(610, 70, 60, 410);

        jButton1.setBackground(new java.awt.Color(255, 102, 0));
        jButton1.setText("START");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(260, 510, 150, 50);

        jLabel3.setFont(new java.awt.Font("Segoe Print", 0, 11)); // NOI18N
        jLabel3.setText("SHKENCA KOMPJUTERIKE 2");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(760, 550, 170, 40);
        getContentPane().add(rezultati);
        rezultati.setBounds(490, 510, 170, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/UBT-LOGO (2).png"))); // NOI18N
        jLabel5.setText("jLabel5");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(690, 140, 230, 240);

        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/grass2.jpg"))); // NOI18N
        jLabel4.setText("jLabel4");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 0, 930, 590);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        kaliPare.setLocation(0, kaliPare.getLocation().y);
        kaliDyte.setLocation(0, kaliDyte.getLocation().y);
        kaliTrete.setLocation(0, kaliTrete.getLocation().y);
        kaliKatert.setLocation(0, kaliKatert.getLocation().y);

        KafshaGaruese_SHK2 kaliPare1 = new KafshaGaruese_SHK2 (kaliPare, this);
        KafshaGaruese_SHK2 kaliDyte2 = new KafshaGaruese_SHK2 (kaliDyte, this);
        KafshaGaruese_SHK2 kaliTrete3 = new KafshaGaruese_SHK2 (kaliTrete, this);
        KafshaGaruese_SHK2 kaliKatert4 = new KafshaGaruese_SHK2 (kaliKatert, this);

        kaliPare1.start();
        kaliDyte2.start();
        kaliTrete3.start();
        kaliKatert4.start();
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Hipodromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Hipodromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Hipodromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Hipodromi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Hipodromi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel finish;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel kaliDyte;
    private javax.swing.JLabel kaliKatert;
    private javax.swing.JLabel kaliPare;
    private javax.swing.JLabel kaliTrete;
    private javax.swing.JLabel rezultati;
    // End of variables declaration//GEN-END:variables
}
